#let thesis-info = (
  degree: "硕士",
  degree_type: "学术学位",
  degree_en: "Master of Engineering",
  title: "某某某研究",
  title_en: "Research on Something Something",
  author: "某某某",
  author_en: "Moumou Mou",
  student_id: "2XXXXXXX",
  school: "某某学院",
  school_en: "School of Something",
  discipline_category: "工学",
  discipline_category_en: "Engineering",
  first_level_discipline: "一级学科名称",
  first_level_discipline_en: "First-level Discipline Name",
  second_level_discipline: "二级学科名称",
  second_level_discipline_en: "Second-level Discipline Name",
  research_direction: "研究方向名称",
  research_direction_en: "Research Direction Name",
  supervisor: "某某某 教授",
  supervisor_en: "Prof. Moumou Mou",
  joint_training: "",
  date_zh: "二〇二六年五月",
  date_en: "May 2026",
  logo: "assets/tongji-logo.jpeg",
)
